<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-GestionUsuarios-438c2f4f-0c00-4e10-8f05-07254a554d67</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.15.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.14" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.14" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.14" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.12" />
  </ItemGroup>

</Project>
